import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show SynchronousFuture;

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'sgnplgn': 'دخول / تسجيل',
      'Or': 'أو',
      'skp': 'تخطي',
      'bcyato': 'بالأستمرار أنت توافق علي',
      'trmscndtn': 'الشروط و الأحكام',
      'nndd': ' و ',
      'prvplcy': 'سياسة الخصوصية',
      'cntctus': 'اتصل بنا',
      'mycht': 'محادثاتي',
      'ntf': 'التنبيهات',
      'prfl': 'صفحة شخصيّة',
      'slctcntry': 'اختر دولتك',
      'srch': 'ابحث',
      'Prsnl': 'الشخصيّة',
      'rfrshng': 'جاري التحميل ...',
      'nmrrcrds': 'لا يوجد ',
      'ldng': 'جاري التحميل',
      'ldmr': 'عرض المزيد',
      'msg': 'محادثة',
      'cmnt': 'تعليق',
      'cht': 'محادثه',
      'nxt': 'التالي',
      'nic': 'لا يوجد اتصال بالانترنت',
      'View More': 'اعرض المزيد',
      'Search...': ' ...بحث',
      'flwng': 'اتابع',
      'flw': 'تابع',
      'flwrs': 'المتابعون',
      'Edit Profile': 'تعديل الملف الشخصي',
      'chlng': 'تغيير اللغة',
      'slctlng': 'اختار اللغة',
      'scntry': 'اختار الدولة',
      'lnge': 'اللغة',
      'hlp': 'المساعدة',
      'myprfl': 'ملفي الشخصي',
      'adpht': 'اضف صورة',
      'eml': 'البريد الالكتروني',
      'lgt': 'الخروج',
      'eemlphn': 'ادخل البريد الالكتروني او رقم الهاتف',
      'emlphntvld': 'البريد الالكتروني او رقم الهاتف غير صالح',
      'etrpswrd': 'ادخل كلمة المرور',
      'pswrdntvld': 'كلمة المرور غير صالحة ',
      'lgn': 'الدخول',
      'emlrph': 'البريد الالكتروني او رقم الهاتف',
      'psswrd': 'كلمة المرور',
      'frgtpswrd': 'هل نسيت كلمة المرور',
      'sgnup': 'التسجيل',
      'emlphntrgsrd': 'البريد الالكتروني او رقم الهاتف غير مسجل',
      'gndr': 'النوع',
      'dobrth': 'تاريخ الميلاد',
      'nvldpswrd8': 'كلمة المرور غير صالحة. يجب ان لا تقل عن ٨ احرف',
      'ml': 'ذكر',
      'fml': 'انثي',
      'penm': 'من فضلك ادخل الاسم الاول',
      'frstnm': ' الاسم الاول',
      'pelnm': 'من فضلك ادخل الاسم الاخير',
      'lstnm': ' الاسم الاخير',
      'plzvldphn': 'من فضلك ادخل رقم هاتف صحيح',
      'mob': ' رقم الهاتف',
      'pswdnt': ' كلمة المرور و تاكيد كلمة المرور غير متطابقان',
      'cnfrmpswrd': 'تاكيد كلمة المرور',
      'rtry': 'حاول مره اخري',
      'emlntvld': 'البريد الالكتروني غير صالح',
      'xcptn': 'حدث خطا. من فضلك حاول مره اخري',
      'Please wait....': '...انتظر من فضلك',
      'nopsts': 'لم يتم العثور على',
      'AbtCnfzz': ' عن التطبيق ',
      'ausywtdlt': 'هل تريد حذف الحساب',
      'ausywtlgt': 'هل تريد تسجيل الخروج ',
      'cncl': 'الغاء',
      'cmnts': 'التعليقات',
      'thm': 'الوضع الليلي',
      'dltaccnt': 'حذف الحساب',
      'dlt': 'حذف',
      'mn': 'الصفحة الرئيسية',
      'lk': 'اعجبني',
      'lks': 'اعجاب',
      'msgstng': 'اعدادات الرسائل',
      'mtlfwlrs': 'متابع مشترك',
      'kkk': 'نعم',
      'rmv': 'حذف',
      'rprtpst': 'ابلاغ عن منشور',
      'rprtusr': 'ابلاغ عن مستخدم',
      'sve': 'حفظ',
      'svdpsts': 'المنشورات المحفوظه',
      'Posts': 'المنشورات',
      'snd': 'ارسل',
      'wrtmsg': 'Write a Message',
      'wrtmsg': 'اكتب رسالة',
      'stngs': 'الاعدادات',
      'shr': 'مشاركة',
      'shwpinf': 'عرض البيانات الشخصية',
      'pinfo': 'البيانات الشخصية',
      'wrtcmnt': 'اكتب تعليق',
      'cnfrmtn': 'تاكيد',
      'blckprsn': 'الاشخاص المحظورين',
      'Persons': 'الاشخاص',
      'blck': 'حظر',
      'mre': 'المزيد',
      'cplnkprfl': 'نسخ الرابط الي الملف الشخصيّ',
      'nflw': 'الغاء المتابعة',
      'rsr': 'توصية بالمتابعة',
      'bkphot': 'صورة الخلفية',
      'bkclr': 'لون الخلفية',
      'acpost': 'النشاط علي المنشور ',
      'sthem': 'اختار الوضع',
      'lthem': 'وضع النهار',
      'dthem': 'وضع الليل',
      'prcd': 'استمرار',
      'wrttl': 'اكتب عنوانًا',
      "rcrd": "تسجيل صوت",
      "plstryagn": "الرجاء المحاولة مرة أخرى",
      "eerr": "خطأ",
      'updtprflpht': 'تحديث صورة الملف الشخصي',
      'updtcvrpht': 'تحديث صورة الغلاف',
      'wrtmsg': 'اكتب رسالة',
      "intrnt": "الإنترنت",
      'updtpswrd': 'تحديث كلمة المرور',
      'cnfrmnwpswrd': 'تأكيد كلمة المرور الجديدة',
      'ccdd': 'الكود',
      'nwpswrd': 'كلمة مرور جديدة',
      'allrghtsrsrvd': 'جميع الحقوق محفوظة',
      "bycmr": "بواسطة الكاميرا",
      'frmglry': 'من معرض الصور',
      "Chspht": "اختر صورة",
      "peveopn": "الرجاء إدخال بريد إلكتروني صالح أو رقم هاتف",
      "eyeophntrp":
          "أدخل عنوان بريدك الإلكتروني أو رقم هاتفك لإعادة تعيين كلمة المرور",
      'rstpswrd': 'إعادة تعيين كلمة المرور',
      'chtlst': 'قائمة الدردشة',
      'nblck': 'Unblock',
    },
    'en': {
      'nblck': 'Unblock',
      'chtlst': 'Chat List',
      'wrttl': 'Write a Title',
      'rcrd': 'Record an Audio',
      'plstryagn': 'Please try again',
      'eerr': 'Error',
      'updtprflpht': 'Update Profile Photo',
      'updtcvrpht': 'Update Cover Photo',
      'wrtmsg': 'Write a Message',
      'intrnt': 'Internet',
      'updtpswrd': 'Update Password',
      'cnfrmnwpswrd': 'Confirm New Password',
      'ccdd': 'Code',
      'nwpswrd': 'New Password',
      'allrghtsrsrvd': 'All rights reserved',
      'bycmr': 'By Camera',
      'frmglry': 'From Photo Gallery',
      'Chspht': 'Choose a Photo',
      'peveopn': 'Please enter valid email or phone number',
      'eyeophntrp':
          'Enter your email address or phone number to reset password',
      'rstpswrd': 'Reset Password',
      'prcd': 'Proceed',
      'dthem': 'Dark Theme',
      'lthem': 'Light Theme',
      'sthem': 'Select a Theme',
      'slctlng': 'Select a Language',
      'scntry': 'Select a Country',
      'Prsnl': 'Personal',
      'acpost': 'Activity on post',
      'bkclr': 'Background Color',
      'bkphot': 'Background Photo',
      'rsr': 'Recommend this User',
      'nflw': 'Unfollow',
      'cplnkprfl': 'Copy Link to This Profile',
      'dlt': 'Delete',
      'mre': 'More',
      'blck': 'Block',
      'flw': 'Follow',
      'blckprsn': 'Blocked Persons',
      'cnfrmtn': 'Confirmation',
      'lnge': 'Language',
      'pinfo': 'Personal Info',
      'AbtCnfzz': 'About iConFezz',
      'wrtcmnt': 'Write a comment',
      'cncl': 'Cancel',
      'cmnts': 'Comments',
      'thm': 'Theme',
      'dltaccnt': 'Delete Account',
      'mn': 'Main',
      'lk': 'Like',
      'lks': 'Likes',
      'msgstng': 'Messaging Settings',
      'mtlfwlrs': 'Mutual Followers',
      'kkk': 'Ok',
      'rmv': 'Remove',
      'rprtpst': 'Report Post',
      'rprtusr': 'Report User',
      'sve': 'Save',
      'snd': 'Send',
      'svdpsts': 'Saved Posts',
      'stngs': 'Settings',
      'shr': 'Share',
      'shwpinf': 'Show Personal Info',
      'sgnplgn': 'Sign Up / Login',
      'bcyato': 'By continuing, you agree to our',
      'trmscndtn': 'Terms and Conditions',
      'nndd': 'and',
      'prvplcy': 'Privacy Policy',
      'cntctus': 'Contact Us',
      'mycht': 'My Chats',
      'ntf': 'Notifications',
      'prfl': 'Profile',
      'slctcntry': 'Select your country',
      'srch': 'Search',
      'rfrshng': 'Refreshing ...',
      'nmrrcrds': 'No more records',
      'ldng': 'Loading ...',
      'ldmr': 'Load More ...',
      'msg': 'Message',
      'cmnt': 'Comment',
      'cht': 'Chat',
      'nxt': 'Next',
      'nic': 'No internet connection.',
      'flwng': 'Following',
      'flwrs': 'Followers',
      'chlng': 'Change Language',
      'hlp': 'Help',
      'myprfl': 'My Profile',
      'adpht': 'Add Photo',
      'mob': 'Phone Number',
      'eml': 'Email',
      'lgt': 'Log Out',
      'eemlphn': 'Enter Email or Phone No.',
      'emlphntvld': 'Email or Phone No. is not valid',
      'etrpswrd': 'Enter Password',
      'pswrdntvld': 'Password is not valid',
      'lgn': 'Log In',
      'emlrph': 'Email or Phone No.',
      'psswrd': 'Password',
      'frgtpswrd': 'Forgot Password?',
      'sgnup': 'Sign Up',
      'emlphntrgsrd': 'The Email or Phone No. is not Registered',
      'gndr': 'Gender',
      'dobrth': 'Date of Birth',
      'nvldpswrd8': 'Invalid password, minimum length is 8 digit',
      'ml': 'Male',
      'fml': 'Female',
      'penm': 'Please enter first name',
      'frstnm': 'First Name',
      'pelnm': 'Please enter last name',
      'lstnm': 'Last Name',
      'plzvldphn': 'Please enter a valid phone number',
      'pswdnt': 'Password and confirm password are not identical',
      'cnfrmpswrd': 'Confirm Password',
      'rtry': 'Retry',
      'emlntvld': 'Email is not valid',
      'xcptn': 'Something went wrong please try again',
      'nopsts': 'No Record Found.',
      'ausywtlgt': 'Are you sure you want to log out from application?',
      'ausywtdlt': 'Are you sure you want to delete your account?',
    },
    'fr': {
      'nblck': 'Débloquer',
      'chtlst': 'Liste de chat',
      'wrttl': 'Ecrire un titre',
      'rcrd': 'Enregistrer un audio',
      'plstryagn': 'Veuillez réessayer',
      'eerr': 'Erreur',
      'updtprflpht': 'Mettre à jour la photo de profil',
      'updtcvrpht': 'Mettre à jour la photo de couverture',
      'wrtmsg': 'Écrire un message',
      'intrnt': 'Internet',
      'updtpswrd': 'Mettre à jour le mot de passe',
      'cnfrmnwpswrd': 'Confirmer le nouveau mot de passe',
      'ccdd': 'Code',
      'nwpswrd': 'Nouveau mot de passe',
      'allrghtsrsrvd': 'Tous droits réservés',
      'bycmr': 'Par caméra',
      'frmglry': 'De la galerie de photos',
      'Chspht': 'Choisissez une photo',
      'peveopn': 'Veuillez saisir un e-mail ou un numéro de téléphone valide',
      'eyeophntrp':
          'Entrez votre adresse e-mail ou numéro de téléphone pour réinitialiser le mot de passe',
      'rstpswrd': 'Réinitialiser le mot de passe',
      'prcd': 'Procéder',
      'dthem': 'Mode nuit',
      'lthem': 'Mode jour',
      'sthem': 'Sélectionnez un thème',
      'slctlng': 'Sélectionnez une langue',
      'scntry': 'Sélectionnez un pays',
      'Prsnl': 'Personnel',
      'acpost': 'Activité sur le post',
      'bkclr': 'Couleur de fond',
      'bkphot': 'Photo de fond',
      'rsr': 'Recommander un utilisateur',
      'nflw': 'Se désabonner',
      'cplnkprfl': 'Copier le lien vers le profil',
      'dlt': 'Supprimer',
      'mre': 'plus',
      'blck': 'Bloquer',
      'flw': 'Suivre',
      'blckprsn': 'Personnes bloquées',
      'cnfrmtn': 'Confirmation',
      'lnge': 'Langue',
      'pinfo': 'Informations personnelles',
      'AbtCnfzz': 'À propos d\'iConFezz',
      'wrtcmnt': 'Ecrire un commentaire',
      'cncl': 'Annuler',
      'cmnts': 'Commentaires',
      'thm': 'Mode sombre',
      'dltaccnt': 'Supprimer le compte',
      'mn': 'Main',
      'lk': 'Aime',
      'lks': 'Aimes',
      'msgstng': 'Paramètres de messagerie',
      'mtlfwlrs': 'Abonnés mutuels',
      'kkk': 'Oui',
      'rmv': 'Supprimer',
      'rprtpst': 'Signaler le Post',
      'rprtusr': 'Signaler l\'utilisateur',
      'sve': 'Enregistrer',
      'snd': 'Envoyer',
      'svdpsts': 'Les Posts enregistrés',
      'stngs': 'Paramètres',
      'shr': 'partage',
      'shwpinf': 'Afficher les informations personnelles',
      'sgnplgn': 'Inscription / Connexion',
      'bcyato': 'En continuant, vous acceptez nos',
      'trmscndtn': 'Termes et Conditions',
      'nndd': ' et ',
      'prvplcy': 'Politique de confidentialité',
      'cntctus': 'Contactez-nous',
      'mycht': 'Mes chats',
      'ntf': 'Notifications',
      'prfl': 'Profil',
      'slctcntry': 'Sélectionnez votre pays',
      'rfrshng': 'Rafraîchissant ...',
      'nmrrcrds': 'Pas plus d\'enregistrements',
      'ldng': 'Chargement ...',
      'ldmr': 'Charger plus ...',
      'msg': 'Message',
      'cmnt': 'Commentaire',
      'cht': 'Chat',
      'nxt': 'Suivant',
      'nic': 'Pas de connexion Internet.',
      'flwng': 'Suivant',
      'flwrs': 'Suiveurs',
      'Invite Your Friends': 'Invitez vos amis',
      'chlng': 'Changer la langue',
      'hlp': 'À l\'aide',
      'myprfl': 'Mon profil',
      'adpht': 'Ajouter une photo',
      'mob': 'Numéro de téléphone',
      'Save and Post': 'Enregistrer et publier',
      'eml': 'Email',
      'lgt': 'Déconnexion',
      'eemlphn': 'Entrer l\'email ou le n ° de téléphone',
      'emlphntvld': 'L\'email ou le numéro de téléphone n\'est pas valide',
      'etrpswrd': 'Entrez un mot de passe',
      'pswrdntvld': 'Le mot de passe n\'est pas valide',
      'lgn': 'Connexion',
      'emlrph': 'Email ou numéro de téléphone',
      'psswrd': 'Mot de passe',
      'frgtpswrd': 'Mot de passe oublié?',
      'sgnup': 'Inscription',
      'emlphntrgsrd':
          'L\'e-mail ou le numéro de téléphone n\'est pas enregistré',
      'gndr': 'Genre',
      'dobrth': 'Date de naissance',
      'nvldpswrd8':
          'Mot de passe invalide, la longueur minimale est de 8 chiffres',
      'ml': 'Homme',
      'fml': 'Femme',
      'penm': 'Veuillez saisir le prénom',
      'frstnm': 'Prénom',
      'pelnm': 'Veuillez saisir le nom de famille',
      'lstnm': 'Nom de famille',
      'plzvldphn': 'Veuillez saisir un numéro de téléphone valide',
      'pswdnt':
          'Le mot de passe et le mot de passe de confirmation ne sont pas identiques.',
      'cnfrmpswrd': 'Confirmer le mot de passe',
      'rtry': 'Réessayer',
      'emlntvld': 'L\'e-mail n\'est pas valide',
      'xcptn': 'Quelque chose s\'est mal passé, veuillez réessayer',
      'nopsts': 'Aucun enregistrement trouvé.',
      'ausywtlgt':
          'Êtes-vous sûr de vouloir vous déconnecter de l\'application?',
      'ausywtdlt': "Voulez-vous vraiment supprimer votre compte?",
    },
    'ru': {
      'nblck': 'Разблокировать',
      'chtlst': 'Список чатов',
      'wrttl': 'Написать заголовок',
      'rcrd': 'Запись аудио',
      'plstryagn': 'Пожалуйста, попробуйте еще раз',
      'eerr': 'Ошибка',
      'updtprflpht': 'Обновить фотографию профиля',
      'updtcvrpht': 'Обновить обложку',
      'wrtmsg': 'Написать сообщение',
      'intrnt': 'Интернет',
      'updtpswrd': 'Обновить пароль',
      'cnfrmnwpswrd': 'Подтвердить новый пароль',
      'ccdd': 'Код',
      'nwpswrd': 'Новый пароль',
      'allrghtsrsrvd': 'Все права защищены',
      'bycmr': 'камерой',
      'frmglry': 'Из фотогалереи',
      'Chspht': 'Выберите фотографию',
      'peveopn':
          'Пожалуйста, введите действительный адрес электронной почты или номер телефона',
      'eyeophntrp':
          'Введите свой адрес электронной почты или номер телефона для сброса пароля',
      'rstpswrd': 'Сбросить пароль',
      'prcd': 'Продолжить',
      'dthem': 'Темная тема',
      'lthem': 'Светлая тема',
      ' sthem': 'Выберите тему',
      'сленг': 'Выбрать язык',
      'scntry': 'Выберите страну',
      'Prsnl': 'Личный',
      'acpost': 'Активность на почте',
      'bkclr': 'Цвет фона',
      'bkphot': 'Фоновая фотография',
      'rsr': 'Рекомендовать этого пользователя',
      'nflw': 'Отписаться',
      'cplnkprfl': 'Скопировать ссылку на этот профиль',
      'dlt': 'Удалить',
      'mre': 'Больше',
      'blck': 'блок',
      'flw': 'следить',
      'blckprsn': 'заблокированные лица',
      'cnfrmtn': 'Подтверждение',
      'lnge': 'язык',
      'pinfo': 'Личная информация',
      'AbtCnfzz': 'около iConFezz',
      'wrtcmnt': 'Написать комментарий',
      'cncl': 'Отмена',
      'cmnts': 'Комментарии',
      'thm': 'тема',
      'dltaccnt': 'Удалить аккаунт',
      'mn': 'Главный',
      'lk': 'любовь',
      'lks': 'симпатии',
      'msgstng': 'Настройки обмена сообщениями',
      'mtlfwlrs': 'Взаимные последователи',
      'kkk': 'ладно',
      'rmv': 'Удалить',
      'rprtpst': 'Пожаловаться на сообщение',
      'rprtusr': 'Сообщить о пользователе',
      'sve': 'Сохранить',
      'snd': 'Отправить',
      'svdpsts': 'Сохраненные сообщения',
      'stngs': 'Настройки',
      'shr': 'Поделиться',
      'shwpinf': 'Показать личную информацию',
      'sgnplgn': 'Зарегистрироваться / Войти',
      'bcyato': 'Продолжая, вы соглашаетесь с нашими',
      'trmscndtn': 'Условия использования',
      'nndd': 'и',
      'prvplcy': 'Политика конфиденциальности',
      'cntctus': 'Свяжитесь с нами',
      'mycht': 'Мои чаты',
      'ntf': 'Уведомления',
      'prfl': 'Профиль',
      'slctcntry': 'Выберите свою страну',
      'srch': 'Поиск',
      'rfrshng': 'Освежающий ...',
      'nmrrcrds': 'Больше нет записей',
      'ldng': 'Загрузка ...',
      'ldmr': 'Загрузи больше ...',
      'msg': 'сообщение',
      'cmnt': 'Комментарий',
      'cht': 'Чат',
      'nxt': 'следующий',
      'nic': 'Нет подключения к интернету.',
      'flwng': 'следить',
      'flwrs': 'Последователи',
      'chlng': 'Изменить язык',
      'hlp': 'Помощь',
      'myprfl': 'Мой профиль',
      'adpht': 'Добавить фото',
      'mob': 'Номер телефона',
      'eml': 'Эл. адрес',
      'lgt': 'Выйти',
      'eemlphn': 'Введите адрес электронной почты или номер телефона',
      'emlphntvld': 'E-mail или номер телефона недействителен',
      'etrpswrd': 'Введите пароль',
      'pswrdntvld': 'Пароль не действителен',
      'lgn': 'Войти',
      'emlrph': 'Электронная почта или номер телефона',
      'psswrd': 'Пароль',
      'frgtpswrd': 'Забыли пароль?',
      'sgnup': 'Зарегистрироваться',
      'emlphntrgsrd':
          'Номер электронной почты или номер телефона не зарегистрирован',
      'gndr': 'Пол',
      'dobrth': 'Дата рождения',
      'nvldpswrd8': 'Неверный пароль, минимальная длина 8 цифр',
      'ml': 'мужчина',
      'fml': 'женщина',
      'penm': 'Пожалуйста, введите имя',
      'frstnm': 'Имя',
      'pelnm': 'Пожалуйста, введите фамилию',
      'lstnm': 'Фамилия',
      'plzvldphn': 'Пожалуйста, введите правильный номер телефона',
      'pswdnt': 'Пароль и пароль подтверждения не идентичны',
      'cnfrmpswrd': 'Подтвердить пароль',
      'rtry': 'снова разбирать',
      'emlntvld': 'Электронная почта недействительна',
      'xcptn': 'Что-то пошло не так, попробуйте еще раз',
      'nopsts': 'Запись не найдена.',
      'ausywtlgt': 'Вы уверены, что хотите выйти из приложения?',
      'ausywtdlt': 'Вы уверены, что хотите удалить свою учетную запись?',
    },
    'he': {
      'nblck': 'בטל את החסימה',
      'chtlst': 'רשימת צ\'אט',
      'wrttl': 'כתוב כותרת',
      'rcrd': 'הקלט שמע',
      'plstryagn': 'אנא נסה שוב',
      'eerr': 'שגיאה',
      'updtprflpht': 'עדכן את תמונת הפרופיל',
      'updtcvrpht': 'עדכן את תמונת השער',
      'wrtmsg': 'כתוב הודעה',
      'intrnt': 'אינטרנט',
      'updtpswrd': 'עדכן סיסמא',
      'cnfrmnwpswrd': 'אשר סיסמא חדשה',
      'ccdd': 'קוד',
      'nwpswrd': 'סיסמא חדשה',
      'allrghtsrsrvd': 'כל הזכויות שמורות',
      'bycmr': 'לפי מצלמה',
      'frmglry': 'מגלריית התמונות',
      'Chspht': 'בחר תמונה',
      'peveopn': 'אנא הכנס דוא"ל או מספר טלפון חוקיים',
      'eyeophntrp':
          'הזן את כתובת הדוא"ל או את מספר הטלפון שלך כדי לאפס את הסיסמה',
      'rstpswrd': 'אפס סיסמא',
      'prcd': '��משך',
      'dthem': 'נושא אפל',
      'lthem': 'נושא קל',
      'sthem': 'בחר נושא',
      'slctlng': 'בחר שפה',
      'scntry': 'בחר מדינה',
      'Prsnl': 'אישי',
      'acpost': 'פעילות בפוסט',
      'bkclr': 'צבע רקע',
      'bkphot': 'צילום רקע',
      'rsr': 'המלץ על משתמש זה',
      'nflw': 'בטל מעקב',
      'cplnkprfl': 'העתק קישור לפרופיל זה',
      'dlt': 'מחק',
      'mre': 'עוד',
      'blck': 'חסום',
      'flw': 'עקוב',
      'blckprsn': 'אנשים חסומים',
      'cnfrmtn': 'אישור',
      'lnge': 'שפה',
      'pinfo': 'מידע אישי',
      'AbtCnfzz': 'אודות iConFezz',
      'wrtcmnt': 'כתוב תגובה',
      'cncl': 'בטל',
      'cmnts': 'הערות',
      'thm': 'נושא',
      'dltaccnt': 'מחק חשבון',
      'mn': 'ראשי',
      'lk': 'כמו',
      'lks': 'אהבתי',
      'msgstng': 'הגדרות הודעות',
      'mtlfwlrs': 'עוקבים הדדיים',
      'kkk': 'בסדר',
      'rmv': 'הסר',
      'rprtpst': 'דווח על הודעה',
      'rprtusr': 'דווח על משתמש',
      'sve': 'שמור',
      'snd': 'שלח',
      'svdpsts': 'פוסטים שמורים',
      'stngs': 'הגדרות',
      'shr': 'שתף',
      'shwpinf': 'הצג מידע אישי',
      'sgnplgn': 'הירשם / התחבר',
      'bcyato': 'בהמשך, אתה מסכים שלנו',
      'trmscndtn': 'תנאים והגבלות',
      'nndd': 'ו-',
      'prvplcy': 'מדיניות פרטיות',
      'cntctus': 'צור קשר',
      'mycht': 'הצ\'אטים שלי',
      'ntf': 'התראות',
      'prfl': 'פרופיל',
      'slctcntry': 'בחר את המדינה שלך',
      'srch': 'חיפוש',
      'rfrshng': 'מרענן ...',
      'nmrrcrds': 'אין עוד רשומות',
      'ldng': 'טוען ...',
      'ldmr': 'טען עוד ...',
      'msg': 'הודעה',
      'cmnt': 'תגובה',
      'cht': 'צ\'אט',
      'nxt': 'הבא',
      'nic': 'אין חיבור לאינטרנט.',
      'flwng': 'בעקבות',
      'flwrs': 'עוקבים',
      'chlng': 'שנה שפה',
      'hlp': 'עזרה',
      'myprfl': 'הפרופיל שלי',
      'adpht': 'הוסף תמונה',
      'mob': 'מספר טלפון',
      'eml': 'אימייל',
      'lgt': 'התנתק',
      'eemlphn': 'הזן דוא"ל או מספר טלפון',
      'emlphntvld': 'אימייל או מספר טלפון אינם תקפים',
      'etrpswrd': 'הזן סיסמא',
      'pswrdntvld': 'הסיסמה אינה תקפה',
      'lgn': 'התחבר',
      'emlrph': 'אימייל או מספר טלפון',
      'psswrd': 'סיסמא',
      'frgtpswrd': 'שכחת את הסיסמה?',
      'sgnup': 'הרשמה',
      'emlphntrgsrd': 'מספר הדואר האלקטרוני או הטלפון אינו רשום',
      'gndr': 'מין',
      'dobrth': 'תאריך לידה',
      'nvldpswrd8': 'סיסמא לא חוקית, אורך מינימום הוא 8 ספרות',
      'ml': 'זכר',
      'fml': 'נקבה',
      'penm': 'אנא הזן את השם הפרטי',
      'frstnm': 'שם פרטי',
      'pelnm': 'אנא הכנס את שם המשפחה',
      'lstnm': 'שם משפחה',
      'plzvldphn': 'אנא הכנס מספר טלפון חוקי',
      'pswdnt': 'סיסמה וסיסמת אישור אינם זהים',
      'cnfrmpswrd': 'אשר את הסיסמה',
      'rtry': 'נסה שוב',
      'emlntvld': 'אימייל לא תקף',
      'xcptn': 'משהו השתבש בבקשה נסה שוב',
      'nopsts': ' לא נמצאה רשומה.',
      'ausywtlgt': 'האם אתה בטוח שברצונך להתנתק מהיישום?',
      'ausywtdlt': 'האם אתה בטוח שברצונך למחוק את חשבונך?',
    },
    'de': {
      'nblck': 'Entsperren',
      'chtlst': 'Chats-Liste',
      'wrttl': 'Titel schreiben',
      'rcrd': 'Audio aufnehmen',
      'plstryagn': 'Bitte versuchen Sie es noch einmal',
      'eerr': 'Fehler',
      'updtprflpht': 'Profilfoto aktualisieren',
      'updtcvrpht': 'Titelbild aktualisieren',
      'wrtmsg': 'Nachricht schreiben',
      'intrnt': 'Internet',
      'updtpswrd': 'Passwort aktualisieren',
      'cnfrmnwpswrd': 'Neues Passwort bestätigen',
      'ccdd': 'Code',
      'nwpswrd': 'Neues Passwort',
      'allrghtsrsrvd': 'Alle Rechte vorbehalten',
      'bycmr': 'Mit der Kamera',
      'frmglry': 'Aus der Fotogalerie',
      'Chspht': 'Wähle ein Foto',
      'peveopn': 'Bitte geben Sie eine gültige E-Mail oder Telefonnummer ein',
      'eyeophntrp':
          'Geben Sie Ihre E-Mail-Adresse oder Telefonnummer ein, um das Passwort zurückzusetzen',
      'rstpswrd': 'Passwort zurücksetzen',
      'prcd': 'Weiter',
      'dthem': 'Dunkles Thema',
      'lthem': 'Lichtthema',
      'sthem': 'Wähle ein Thema',
      'slctlng': 'Sprache auswählen',
      'scntry': 'Wähle ein Land',
      'Prsnl': 'Personal',
      'acpost': 'Aktivität auf dem Postweg',
      'bkclr': 'Hintergrundfarbe',
      'bkphot': 'Hintergrundfoto',
      'rsr': 'Diesen Benutzer empfehlen',
      'nflw': 'Nicht mehr folgen',
      'cplnkprfl': 'Link zu diesem Profil kopieren',
      'dlt': 'Löschen',
      'mre': 'Mehr',
      'blck': 'Block',
      'flw': 'Folgen',
      'blckprsn': 'Gesperrte Personen',
      'cnfrmtn': 'Bestätigung',
      'lnge': 'Sprache',
      'pinfo': 'Persönliche Daten',
      'AbtCnfzz': 'Über iConFezz',
      'wrtcmnt': 'Kommentar schreiben',
      'cncl': 'Abbrechen',
      'cmnts': 'Kommentare',
      'thm': 'Thema',
      'dltaccnt': 'Konto löschen',
      'mn': 'Main',
      'lk': 'Gefällt mir',
      'lks': 'Vorlieben',
      'msgstng': 'Messaging-Einstellungen',
      'mtlfwlrs': 'Gegenseitige Anhänger',
      'kkk': 'Ok',
      'rmv': 'Entfernen',
      'rprtpst': 'Beitrag melden',
      'rprtusr': 'Benutzer melden',
      'sve': 'Speichern',
      'snd': 'Senden',
      'svdpsts': 'Gespeicherte Beiträge',
      'stngs': 'Einstellungen',
      'shr': 'Teilen',
      'shwpinf': 'Persönliche Daten anzeigen',
      'sgnplgn': 'Registrieren / Anmelden',
      'bcyato': 'Indem Sie fortfahren, stimmen Sie unserer zu',
      'trmscndtn': 'Allgemeine Geschäftsbedingungen',
      'nndd': 'und',
      'prvplcy': 'Datenschutzerklärung',
      'cntctus': 'Kontaktieren Sie uns',
      'mycht': 'Meine Chats',
      'ntf': 'Benachrichtigungen',
      'prfl': 'Profil',
      'slctcntry': 'Wähle dein Land',
      'srch': 'Suche',
      'rfrshng': 'Erfrischend ...',
      'nmrrcrds': 'Keine weiteren Datensätze',
      'ldng': 'Wird geladen ...',
      'ldmr': 'Mehr laden ...',
      'msg': 'Nachricht',
      'cmnt': 'Kommentar',
      'cht': 'Chat',
      'nxt': 'Nächster',
      'nic': 'Keine Internetverbindung.',
      'flwng': 'folgenden',
      'flwrs': 'Anhänger',
      'chlng': 'Sprache ändern',
      'hlp': 'Hilfe',
      'myprfl': 'Mein Profil',
      'adpht': 'Foto hinzufügen',
      'mob': 'Telefonnummer',
      'eml': 'Email',
      'lgt': 'Abmelden',
      'eemlphn': 'Email oder Telefonnummer eingeben',
      'emlphntvld': 'Email oder Telefonnummer ist ungültig',
      'etrpswrd': 'Passwort eingeben',
      'pswrdntvld': 'Passwort ist ungültig',
      'lgn': 'Anmelden',
      'emlrph': 'Email oder Telefonnummer',
      'psswrd': 'Passwort',
      'frgtpswrd': 'Passwort vergessen?',
      'sgnup': 'Anmelden',
      'emlphntrgsrd': 'Die Email oder Telefonnummer ist nicht registriert',
      'gndr': 'Geschlecht',
      'dobrth': 'Geburtsdatum',
      'nvldpswrd8': 'Ungültiges Passwort, Mindestlänge 8 Stellen',
      'ml': 'männlich',
      'fml': 'weiblich',
      'penm': 'Bitte Vorname eingeben',
      'frstnm': 'Vorname',
      'pelnm': 'Bitte Nachname eingeben',
      'lstnm': 'Nachname',
      'plzvldphn': 'Bitte geben Sie eine gültige Telefonnummer ein',
      'pswdnt': 'Passwort und Bestätigungspasswort sind nicht identisch',
      'cnfrmpswrd': 'Passwort bestätigen',
      'rtry': 'Wiederholen',
      'emlntvld': 'Email ist ungültig',
      'xcptn': 'Es ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',
      'nopsts': 'Keine Aufzeichnungen gefunden',
      'ausywtlgt': 'Möchten Sie sich wirklich von der Anwendung abmelden?',
      'ausywtdlt': 'Möchten Sie Ihren Account wirklich löschen?',
    },
    'zh': {
      'nblck': '解除封锁',
      'chtlst': '聊天清单',
      'wrttl': '写标题',
      'rcrd': '录制音频',
      'plstryagn': '请再试一次',
      'eerr': '错误',
      'updtprflpht': '更新个人资料照片',
      'updtcvrpht': '更新封面照片',
      'wrtmsg': '写一条消息',
      'intrnt': '互联网',
      'updtpswrd': '更新密码',
      'cnfrmnwpswrd': '确认新密码',
      'ccdd': '代码',
      'nwpswrd': '新密码',
      'allrghtsrsrvd': '保留所有权利',
      'bycmr': '通过摄像机',
      'frmglry': '来自照相馆',
      'Chspht': '选择照片',
      'peveopn': '请输入有效的电子邮件或电话号码',
      'eyeophntrp': '输入您的电子邮件地址或电话号码以重置密码',
      'rstpswrd': '重置密码',
      'prcd': '继续',
      'dthem': '黑暗主题',
      'lthem': '轻主题',
      'sthem': '选择主题',
      'slctlng': '选择一种语言',
      'scntry': '选择国家',
      'Prsnl': '个人',
      'acpost': '发布活动',
      'bkclr': '背景色',
      'bkphot': '背景图片',
      'rsr': '推荐此用户',
      'nflw': '取消关注',
      'cplnkprfl': '将链接复制到此配置文件',
      'dlt': '删除',
      'mre': '更多',
      'blck': '阻止',
      'flw': '关注',
      'blckprsn': '封锁者',
      'cnfrmtn': '确认',
      'lnge': '语言',
      'pinfo': '个人信息',
      'AbtCnfzz': '关于iConFezz',
      'wrtcmnt': '发表评论',
      'cncl': '取消',
      'cmnts': '评论',
      'thm': '主题',
      'dltaccnt': '删除帐户',
      'mn': '主要',
      'lk': '喜欢',
      'lks': '喜欢',
      'msgstng': '邮件设置',
      'mtlfwlrs': '共同关注者',
      'kkk': '确定',
      'rmv': '删除',
      'rprtpst': '报告发布',
      'rprtusr': '报告用户',
      'sve': '保存',
      'snd': '发送',
      'svdpsts': '已保存的帖子',
      'stngs': '设置',
      'shr': '分享',
      'shwpinf': '显示个人信息',
      'sgnplgn': '注册/登录',
      'bcyato': '继续,您同意我们的意见',
      'trmscndtn': '条款和条件',
      'nndd': '和',
      'prvplcy': '隐私政策',
      'cntctus': '联系我们',
      'mycht': '我的聊天室',
      'ntf': '通知',
      'prfl': '个人资料',
      'slctcntry': '选择您的国家',
      'srch': '搜索',
      'rfrshng': '刷新...',
      'nmrrcrds': '没有更多记录',
      'ldng': '正在加载...',
      'ldmr': '加载更多...',
      'msg': '消息',
      'cmnt': '评论',
      'cht': '聊天',
      'nxt': '下一步',
      'nic': '没有互联网连接。',
      'flwng': '以下',
      'flwrs': '跟随者',
      'chlng': '更改语言',
      'hlp': '帮助',
      'myprfl': '我的个人资料',
      'adpht': '添加照片',
      'mob': '电话号码',
      'eml': '电子邮件',
      'lgt': '注销',
      'eemlphn': '输入电子邮件或电话号码',
      'emlphntvld': '电子邮件或电话号码无效',
      'etrpswrd': '输入密码',
      'pswrdntvld': '密码无效',
      'lgn': '登录',
      'emlrph': '电子邮件或电话号码',
      'psswrd': '密码',
      'frgtpswrd': '忘记密码？',
      'sgnup': '注册',
      'emlphntrgsrd': '电子邮件或电话号码未注册',
      'gndr': '性别',
      'dobrth': '出生日期',
      'nvldpswrd8': '无效的密码,最小长度为8位数字',
      'ml': '男',
      'fml': '女性',
      'penm': '请输入名字',
      'frstnm': '名字',
      'pelnm': '请输入姓氏',
      'lstnm': '姓氏',
      'plzvldphn': '请输入一个有效的电话号码',
      'pswdnt': '密码和确认密码不相同',
      'cnfrmpswrd': '确认密码',
      'rtry': '重试',
      'emlntvld': '电子邮件无效',
      'xcptn': '出了点问题,请重试',
      'nopsts': '找不到Ufff记录。',
      'ausywtlgt': '确定要从应用程序注销吗？',
      'ausywtdlt': '确定要删除您的帐户吗？',
    },
    'es': {
      'nblck': 'Desatascar',
      'chtlst': 'Lista de chats',
      'wrttl': 'Escribe un título',
      'rcrd': 'Grabar un audio',
      'plstryagn': 'Inténtalo de nuevo',
      'eerr': 'Error',
      'updtprflpht': 'Actualizar foto de perfil',
      'updtcvrpht': 'Actualizar foto de portada',
      'wrtmsg': 'Escribir un mensaje',
      'intrnt': 'Internet',
      'updtpswrd': 'Actualizar contraseña',
      'cnfrmnwpswrd': 'Confirmar nueva contraseña',
      'ccdd': 'Código',
      'nwpswrd': 'Nueva contraseña',
      'allrghtsrsrvd': 'Todos los derechos reservados',
      'bycmr': 'Por cámara',
      'frmglry': 'De la galería de fotos',
      'Chspht': 'Elige una foto',
      'peveopn': 'Ingrese un correo electrónico o número de teléfono válido',
      'eyeophntrp':
          'Ingrese su dirección de correo electrónico o número de teléfono para restablecer la contraseña',
      'rstpswrd': 'Restablecer contraseña',
      'prcd': 'Continuar',
      'dthem': 'Tema oscuro',
      'lthem': 'Tema ligero',
      'sthem': 'Seleccionar un tema',
      'slctlng': 'Seleccionar un idioma',
      'scntry': 'Seleccione un país',
      'Prsnl': 'Personal',
      'acpost': 'Actividad en la publicación',
      'bkclr': 'Color de fondo',
      'bkphot': 'Foto de fondo',
      'rsr': 'Recomendar a este usuario',
      'nflw': 'Dejar de seguir',
      'cplnkprfl': 'Copiar enlace a este perfil',
      'dlt': 'Eliminar',
      'mre': 'Más',
      'blck': 'Bloque',
      'flw': 'Seguir',
      'blckprsn': 'Personas bloqueadas',
      'cnfrmtn': 'Confirmación',
      'lnge': 'Idioma',
      'pinfo': 'Información personal',
      'AbtCnfzz': 'Acerca de iConFezz',
      'wrtcmnt': 'Escribe un comentario',
      'cncl': 'Cancelar',
      'cmnts': 'Comentarios',
      'thm': 'Tema',
      'dltaccnt': 'Eliminar cuenta',
      'mn': 'Principal',
      'lk': 'Me gusta',
      'lks': 'Me gusta',
      'msgstng': 'Configuración de mensajería',
      'mtlfwlrs': 'Seguidores mutuos',
      'kkk': 'Bueno',
      'rmv': 'Eliminar',
      'rprtpst': 'Informar publicación',
      'rprtusr': 'Informar usuario',
      'sve': 'Guardar',
      'snd': 'Enviar',
      'svdpsts': 'Publicaciones guardadas',
      'stngs': 'Configuración',
      'shr': 'Compartir',
      'shwpinf': 'Mostrar información personal',
      'sgnplgn': 'Registrarse / Iniciar sesión',
      'bcyato': 'Al continuar, acepta nuestro',
      'trmscndtn': 'Términos y condiciones',
      'nndd': 'y',
      'prvplcy': 'Política de privacidad',
      'cntctus': 'Contáctenos',
      'mycht': 'Mis chats',
      'ntf': 'Notificaciones',
      'prfl': 'Perfil',
      'slctcntry': 'Seleccione su país',
      'srch': 'Buscar',
      'rfrshng': 'Refrescando ...',
      'nmrrcrds': 'No más registros',
      'ldng': 'Cargando ...',
      'ldmr': 'Cargar más ...',
      'msg': 'Mensaje',
      'cmnt': 'Comentario',
      'cht': 'Chat',
      'nxt': 'Siguiente',
      'nic': 'Sin conexión a internet',
      'flwng': 'Siguiendo',
      'flwrs': 'Seguidores',
      'chlng': 'Cambiar idioma',
      'hlp': 'Ayuda',
      'myprfl': 'Mi perfil',
      'adpht': 'Agregar foto',
      'mob': 'Número de teléfono',
      'eml': 'Correo electrónico',
      'lgt': 'Cerrar sesión',
      'eemlphn': 'Ingresar correo electrónico o número de teléfono',
      'emlphntvld': 'Correo electrónico o número de teléfono no es válido',
      'etrpswrd': 'Ingresar contraseña',
      'pswrdntvld': 'La contraseña no es válida',
      'lgn': 'Iniciar sesión',
      'emlrph': 'Correo electrónico o número de teléfono',
      'psswrd': 'Contraseña',
      'frgtpswrd': '¿Olvidó su contraseña?',
      'sgnup': 'Registrarse',
      'emlphntrgsrd':
          'El correo electrónico o número de teléfono no está registrado',
      'gndr': 'Género',
      'dobrth': 'Fecha de nacimiento',
      'nvldpswrd8': 'Contraseña no válida, la longitud mínima es de 8 dígitos',
      'ml': 'Hombre',
      'fml': 'Femenino',
      'penm': 'Ingrese el nombre',
      'frstnm': 'Nombre',
      'pelnm': 'Por favor ingrese el apellido',
      'lstnm': 'Apellido',
      'plzvldphn': 'Ingrese un número de teléfono válido',
      'pswdnt':
          'La contraseña y la contraseña de confirmación no son idénticas',
      'cnfrmpswrd': 'Confirmar contraseña',
      'rtry': 'Reintentar',
      'emlntvld': 'El correo electrónico no es válido',
      'xcptn': 'Algo salió mal, inténtalo de nuevo',
      'nopsts': 'No se encontró registro',
      'ausywtlgt': '¿Está seguro de que desea cerrar sesión en la aplicación?',
      'ausywtdlt': '¿Está seguro de que desea eliminar su cuenta?',
    },
    'uk': {
      'nblck': 'Розблокувати',
      'chtlst': 'Список чатів',
      'wrttl': 'Написати назву',
      'rcrd': 'Запис аудіозапису',
      'plstryagn': 'Будь ласка, спробуйте ще раз',
      'eerr': 'Помилка',
      'updtprflpht': 'Оновити фотографію профілю',
      'updtcvrpht': 'Оновити обкладинку ',
      'wrtmsg': 'Написати повідомлення',
      'intrnt': 'Інтернет',
      'updtpswrd': 'Оновити пароль',
      'cnfrmnwpswrd': 'Підтвердити новий пароль',
      'ccdd': 'Код',
      'nwpswrd': 'Новий пароль',
      'allrghtsrsrvd': 'Усі права захищені',
      'bycmr': 'За камерою',
      'frmglry': 'З фотогалереї',
      'Chspht': 'Оберіть фотографію',
      'peveopn':
          'Будь ласка, введіть дійсну електронну пошту чи номер телефону',
      'eyeophntrp':
          'Введіть свою електронну адресу або номер телефону для скидання пароля',
      'rstpswrd': 'Скинути пароль',
      'prcd': 'Продовжити',
      'dthem': 'Темна тема',
      'lthem': 'Світла тема',
      'sthem': 'Виберіть тему',
      'slctlng': 'Виберіть мову',
      'scntry': 'Виберіть країну',
      'Prsnl': 'Особистий',
      'acpost': 'Активність на посаді',
      'bkclr': 'Колір фону',
      'bkphot': 'Фонова фотографія',
      'rsr': 'Рекомендувати цього користувача',
      'nflw': 'Скасувати наступні дії',
      'cplnkprfl': 'Скопіювати посилання на цей профіль',
      'dlt': 'Видалити',
      'mre': 'Більше',
      'blck': 'Блокувати',
      'flw': 'Дотримуйтесь',
      'blckprsn': 'Заблоковані особи',
      'cnfrmtn': 'Підтвердження',
      'lnge': 'Мова',
      'pinfo': 'Особиста інформація',
      'AbtCnfzz': 'Про iConFezz',
      'wrtcmnt': 'Написати коментар',
      'cncl': 'Скасувати',
      'cmnts': 'Коментарі',
      'thm': 'Тема',
      'dltaccnt': 'Видалити обліковий запис',
      'mn': 'Головна',
      'lk': 'симпатії',
      'lks': 'Подобається',
      'msgstng': 'Налаштування повідомлень',
      'mtlfwlrs': 'Взаємні послідовники',
      'kkk': 'Добре',
      'rmv': 'Видалити',
      'rprtpst': 'Повідомлення про повідомлення',
      'rprtusr': 'Повідомити користувача',
      'sve': 'Зберегти',
      'snd': 'Надіслати',
      'svdpsts': 'Збережені повідомлення',
      'stngs': 'Налаштування',
      'shr': 'Поділитися',
      'shwpinf': 'Показати особисту інформацію',
      'sgnplgn': 'Зареєструватися / увійти',
      'bcyato': "Продовжуючи, ви погоджуєтесь з нашими",
      'trmscndtn': 'Загальні положення та умови',
      'nndd': 'і',
      'prvplcy': 'Політика конфіденційності',
      'cntctus': 'Зв\'яжіться з нами',
      'mycht': 'Мої чати',
      'ntf': 'Повідомлення',
      'prfl': 'Профіль',
      'slctcntry': 'Виберіть країну',
      'srch': 'Пошук',
      'rfrshng': 'Освіжаючий ...',
      'nmrrcrds': 'Більше не записується',
      'ldng': 'Завантаження ...',
      'ldmr': 'Завантажити більше ...',
      'msg': 'Повідомлення',
      'cmnt': 'коментар',
      'cht': 'Чат',
      'nxt': 'Далі',
      'nic': 'Немає підключення до Інтернету.',
      'flwng': 'Після',
      'flwrs': 'Підписники',
      'chlng': 'Змінити мову',
      'hlp': 'Довідка',
      'myprfl': 'Мій профіль',
      'adpht': 'Додати фотографію',
      'mob': 'Номер телефону',
      'eml': 'Електронна пошта',
      'lgt': 'Вийти',
      'eemlphn': 'Введіть електронну пошту або номер телефону',
      'emlphntvld': 'Електронна пошта або номер телефону недійсні',
      'etrpswrd': 'Введіть пароль',
      'pswrdntvld': 'Пароль недійсний',
      'lgn': 'Увійти',
      'emlrph': 'Електронна пошта або номер телефону',
      'psswrd': 'Пароль',
      'frgtpswrd': 'Забули пароль?',
      'sgnup': 'Зареєструватися',
      'emlphntrgsrd': 'Номер електронної пошти чи телефону не зареєстрований',
      'gndr': 'Стать',
      'dobrth': 'Дата народження',
      'nvldpswrd8': 'Недійсний пароль, мінімальна довжина - 8 цифр',
      'ml': 'Чоловік',
      'fml': 'Жінки',
      'penm': 'Будь ласка, введіть ім\'я',
      'frstnm': 'Ім\'я',
      'pelnm': 'Будь ласка, введіть прізвище',
      'lstnm': 'Прізвище',
      'plzvldphn': 'Будь ласка, введіть дійсний номер телефону',
      'pswdnt': 'Пароль і пароль підтвердження не ідентичні',
      'cnfrmpswrd': 'Підтвердити паро��ь',
      'rtry': 'Повторити',
      'emlntvld': 'Електронна пошта недійсна',
      'xcptn': 'Щось пішло не так, будь ласка, спробуйте знову',
      'nopsts': 'Запис не знайдено.',
      'ausywtlgt': 'Ви впевнені, що хочете вийти з програми?',
      'ausywtdlt': 'Ви впевнені, що хочете видалити свій рахунок?',
    },
    'af': {
      'nblck': 'ontblok',
      'chtlst': 'Geselslys',
      'wrttl': 'Skryf \'n titel',
      'rcrd': 'Neem \'n klank op',
      'plstryagn': 'Probeer asseblief weer',
      'eerr': 'Fout',
      'updtprflpht': 'Werk profielfoto op',
      'updtcvrpht': 'Opdateer omslagfoto',
      'wrtmsg': 'Skryf \'n boodskap',
      'intrnt': 'internet',
      'updtpswrd': 'Wagwoord bywerk',
      'cnfrmnwpswrd': 'Bevestig nuwe wagwoord',
      'ccdd': 'Kode',
      'nwpswrd': 'Nuwe wagwoord',
      'allrghtsrsrvd': 'Alle regte voorbehou',
      'bycmr': 'Per kamera',
      'frmglry': 'Vanaf fotogallery',
      'Chspht': 'Kies \'n foto',
      'peveopn': 'Voer \'n geldige e-pos of telefoonnommer in',
      'eyeophntrp':
          'Voer u e-posadres of telefoonnommer in om die wagwoord terug te stel',
      'rstpswrd': 'Wagwoord terugstel',
      'prcd': 'Gaan voort',
      'dthem': 'Donker tema',
      'lthem': 'Ligte tema',
      'sthem': 'Kies \'n tema',
      'slctlng': 'Kies een taal',
      'scntry': 'Kies een land',
      'Prsnl': 'Persoonlik',
      'acpost': 'Aktiwiteit op die pos',
      'bkclr': 'Agtergrondkleur',
      'bkphot': 'Agtergrondfoto',
      'rsr': 'Beveel hierdie gebruiker aan',
      'nflw': 'Ontvolg',
      'cplnkprfl': 'Kopieer skakel na hierdie profiel',
      'dlt': 'Verwyder',
      'mre': 'Meer',
      'blck': 'Blok',
      'flw': 'Volg',
      'blckprsn': 'Geblokkeerde persone',
      'cnfrmtn': 'Bevestiging',
      'lnge': 'Taal',
      'pinfo': 'Persoonlike inligting',
      'AbtCnfzz': 'Oor iConFezz',
      'wrtcmnt': 'Skryf \'n opmerking',
      'cncl': 'Kanselleer',
      'cmnts': 'Opmerkings',
      'thm': 'Tema',
      'dltaccnt': 'Account verwyder',
      'mn': 'hoof',
      'lk': 'Soos',
      'lks': 'Hou van',
      'msgstng': 'Boodskappinstellings',
      'mtlfwlrs': 'Wedersydse volgelinge',
      'kkk': 'Ok',
      'rmv': 'Verwyder',
      'rprtpst': 'Verslag boodskap',
      'rprtusr': 'Rapporteer gebruiker',
      'sve': 'Stoor',
      'snd': 'Stuur',
      'svdpsts': 'Opgeslagen poste',
      'stngs': 'Instellings',
      'shr': 'Deel',
      'shwpinf': 'Wys persoonlike inligting',
      'sgnplgn': 'Aanmelden / aanmeld',
      'bcyato': 'Deur voort te gaan, stem u in tot ons',
      'trmscndtn': 'Voorwaardes',
      'nndd': 'en',
      'prvplcy': 'Privaatheidsbeleid',
      'cntctus': 'Kontak ons',
      'mycht': 'My geselsies',
      'ntf': 'Kennisgewings',
      'prfl': 'Profiel',
      'slctcntry': 'Kies jou land',
      'srch': 'Soek',
      'rfrshng': 'Verfrissend ...',
      'nmrrcrds': 'Geen rekords meer nie',
      'ldng': 'Laai ...',
      'ldmr': 'Meer laai ...',
      'msg': 'Boodskap',
      'cmnt': 'Opmerking',
      'cht': 'Gesels',
      'nxt': 'Volgende',
      'nic': 'Geen internetverbinding.',
      'flwng': 'Volgende',
      'flwrs': 'Volgers',
      'chlng': 'Taal verander',
      'hlp': 'hulp',
      'myprfl': 'My profiel',
      'adpht': 'Voeg foto by',
      'mob': 'Telefoonnommer',
      'eml': 'e-pos',
      'lgt': 'Afmeld',
      'eemlphn': 'Voer e-pos of telefoonnommer in',
      'emlphntvld': 'E-pos of telefoonnommer is nie geldig nie',
      'etrpswrd': 'Wagwoord invoer',
      'pswrdntvld': 'Wagwoord is nie geldig nie',
      'lgn': 'Meld aan',
      'emlrph': 'E-pos of telefoonnommer',
      'psswrd': 'Wagwoord',
      'frgtpswrd': 'Wagwoord vergeet?',
      'sgnup': 'Meld u aan',
      'emlphntrgsrd': 'Die e-pos of telefoonnommer is nie geregistreer nie',
      'gndr': 'Geslag',
      'dobrth': 'Geboortedatum',
      'nvldpswrd8': 'Ongeldige wagwoord, minimum lengte is 8 syfer',
      'ml': 'Manlik',
      'fml': 'Vroulik',
      'penm': 'Voer eerste naam in',
      'frstnm': 'Voornaam',
      'pelnm': 'Voer naam in',
      'lstnm': 'Achternaam',
      'plzvldphn': 'Voer \'n geldige telefoonnommer in',
      'pswdnt': 'Wagwoord en bevestig wagwoord is nie identies nie',
      'cnfrmpswrd': 'Wagwoord bevestig',
      'rtry': 'probeer weer',
      'emlntvld': 'E-pos is nie geldig nie',
      'xcptn': 'Iets het verkeerd gegaan, probeer asseblief weer',
      'nopsts': 'geen rekord gevind.',
      'ausywtlgt': 'Weet u seker dat u van die toepassing wil afmeld?',
      'ausywtdlt': 'Is u seker dat u u rekening wil uitvee?',
    },
    'ja': {
      'nblck': 'ブロックを解除',
      'chtlst': 'チャットリスト',
      'wrttl': 'タイトルを書く',
      'rcrd': '音声を録音する',
      'plstryagn': 'もう一度やり直してください',
      'eerr': 'エラー',
      'updtprflpht': 'プロフィール写真の更新',
      'updtcvrpht': 'カバー写真の更新',
      'wrtmsg': 'メッセージを書く',
      'intrnt': 'インターネット',
      'updtpswrd': 'パスワードの更新',
      'cnfrmnwpswrd': '新しいパスワードの確認',
      'ccdd': 'コード',
      'nwpswrd': '新しいパスワード',
      'allrghtsrsrvd': 'すべての権利を保有',
      'bycmr': 'カメラ別',
      'frmglry': 'フォトギャラリーから',
      'Chspht': '写真の選択',
      'peveopn': '有効なメールまたは電話番号を入力してください',
      'eyeophntrp': 'パスワードをリセットするには,メールアドレスまたは電話番号を入力してください',
      'rstpswrd': 'パスワードのリセット',
      'prcd': '続行',
      'dthem': 'ダークテーマ',
      'lthem': '光のテーマ',
      'sthem': 'テーマの選択',
      'slctlng': '言語の選択',
      'scntry': '国を選択してください',
      'Prsnl': '個人',
      'acpost': '投稿のアクティビティ',
      'bkclr': '背景色',
      'bkphot': '背景写真',
      'rsr': 'このユーザーを推奨',
      'nflw': 'フォロー解除',
      'cplnkprfl': 'このプロファイルへのリンクのコピー',
      'dlt': '削除',
      'mre': 'その他',
      'blck': 'ブロック',
      'flw': 'フォロー',
      'blckprsn': 'ブロックされた人',
      'cnfrmtn': '確認',
      'lnge': '言語',
      'pinfo': '個人情報',
      'AbtCnfzz': 'iConFezzについて',
      'wrtcmnt': 'コメントを書く',
      'cncl': 'キャンセル',
      'cmnts': 'コメント',
      'thm': 'テーマ',
      'dltaccnt': 'アカウントの削除',
      'mn': 'メイン',
      'lk': 'いいね',
      'lks': 'いいね',
      'msgstng': 'メッセージング設定',
      'mtlfwlrs': '相互フォロワー',
      'kkk': 'はい',
      'rmv': '削除',
      'rprtpst': 'レポート投稿',
      'rprtusr': 'ユーザーのレポート',
      'sve': '保存',
      'snd': '送信',
      'svdpsts': '保存された投稿',
      'stngs': '設定',
      'shr': '共有',
      'shwpinf': '個人情報を表示',
      'sgnplgn': 'サインアップ/ログイン',
      'bcyato': '続行することで,私たちに同意します',
      'trmscndtn': '契約条件',
      'nndd': 'そして',
      'prvplcy': 'プライバシーポリシー',
      'cntctus': 'お問い合わせ',
      'mycht': 'マイチャット',
      'ntf': '通知',
      'prfl': 'プロファイル',
      'slctcntry': '国を選択してください',
      'srch': '検索',
      'rfrshng': '更新中...',
      'nmrrcrds': 'これ以上のレコード',
      'ldng': '読み込み中...',
      'ldmr': 'さらに読み込む...',
      'msg': 'メッセージ',
      'cmnt': 'コメント',
      'cht': 'チャット',
      'nxt': '次へ',
      'nic': 'インターネット接続なし',
      'flwng': 'フォロー',
      'flwrs': 'フォロワー',
      'chlng': '言語の変更',
      'hlp': 'ヘルプ',
      'myprfl': 'マイプロフィール',
      'adpht': '写真を追加',
      'mob': '電話番号',
      'eml': 'メール',
      'lgt': 'ログアウト',
      'eemlphn': 'メールまたは電話番号を入力してください',
      'emlphntvld': 'メールまたは電話番号が無効です',
      'etrpswrd': 'パスワードの入力',
      'pswrdntvld': 'パスワードが無効です',
      'lgn': 'ログイン',
      'emlrph': 'メールまたは電話番号',
      'psswrd': 'パスワード',
      'frgtpswrd': 'パスワードをお忘れですか？',
      'sgnup': 'サインアップ',
      'emlphntrgsrd': 'メールまたは電話番号が登録されていません',
      'gndr': '性別',
      'dobrth': '生年月日',
      'nvldpswrd8': '無効なパスワード,最小長は8桁です',
      'ml': '男性',
      'fml': '女性',
      'penm': '名を入力してください',
      'frstnm': '名',
      'pelnm': '姓を入力してください',
      'lstnm': '姓',
      'plzvldphn': '有効な電話番号を入力してください',
      'pswdnt': 'パスワードとパスワードの確認は同一ではありません',
      'cnfrmpswrd': 'パスワードの確認',
      'rtry': '再試行',
      'emlntvld': 'メールが無効です',
      'xcptn': '問題が発生しました。もう一度やり直してください',
      'nopsts': 'Ufffレコードが見つかりません。',
      'ausywtlgt': 'アプリケーションからログアウトしますか？',
      'ausywtdlt': 'アカウントを削除してもよろしいですか？',
    },
    'hi': {
      'nblck': 'अनब्लॉक',
      'chtlst': 'चैट लिस्ट',
      'wrttl': 'एक शीर्षक लिखो',
      'rcrd': 'एक ऑडियो रिकॉर्ड करें',
      'plstryagn': 'कृपया पुनः प्रयास करें',
      'eerr': 'त्रुटि',
      'updtprflpht': 'अपडेट प्रोफाइल फोटो',
      'updtcvrpht': 'अपडेट कवर फोटो',
      'wrtmsg': 'एक संदेश लिखें',
      'intrnt': 'इंटरनेट',
      'updtpswrd': 'अपडेट पासवर्ड',
      'cnfrmnwpswrd': 'नए पासवर्ड की पुष्टि करें',
      'ccdd': 'कोड',
      'nwpswrd': 'न्यू पासवर्ड',
      'allrghtsrsrvd': 'सभी अधिकार सुरक्षित',
      'bycmr ': 'Camera बाय कैमरा',
      'frmglry': 'फ्रॉम फोटो गैलरी',
      'Chspht': 'एक तस्वीर चुनें',
      'peveopn': 'कृपया मान्य ईमेल या फ़ोन नंबर दर्ज करें',
      'eyeophntrp':
          'पासवर्ड रीसेट करने के लिए अपना ईमेल पता या फोन नंबर दर्ज करें',
      'rstpswrd': 'पासवर्ड रीसेट करें',
      'prcd': 'आगे बढ़ना',
      'dthem': 'डार्क थीम',
      'lthem': 'लाइट थीम',
      'sthem': 'Select a Theme',
      'slctlng': 'भाषा चुनें',
      'scntry': 'एक देश का चयन करें',
      'Prsnl': 'व्यक्तिगत',
      'acpost': 'पोस्ट पर गतिविधि',
      'bkclr': 'बैकग्राउंड कलर',
      'bkphot': 'बैकग्राउंड फोटो',
      'rsr': 'इस उपयोगकर्ता की अनुशंसा करें',
      'nflw': 'अनफॉलो',
      'cplnkprfl': 'इस प्रोफ़ाइल की लिंक कॉपी करें',
      'dlt': 'हटाएँ',
      'mre': 'अधिक',
      'blck': 'ब्लॉक',
      'flw': 'फॉलो',
      'blckprsn': 'अवरुद्ध व्यक्ति',
      'cnfrmtn': 'पुष्टि',
      'lnge': 'भाषा',
      'pinfo': 'व्यक्तिगत जानकारी',
      'AbtCnfzz': 'आईकॉन्फेज के बारे में',
      'wrtcmnt': 'एक टिप्पणी लिखें',
      'cncl': 'रद्द करें',
      'cmnts': 'टिप्पणियाँ',
      'thm': 'थीम',
      'dltaccnt': 'खाता हटाएं',
      'mn': 'मेन',
      'lk': 'लाइक',
      'lks': 'पसंद',
      'msgstng': 'संदेश सेटिंग्स',
      'mtlfwlrs': 'म्यूचुअल फॉलोअर्स',
      'kkk': 'Ok',
      'rmv': 'निकालें',
      'rprtpst': 'रिपोर्ट पोस्ट',
      'rprtusr': 'रिपोर्ट उपयोगकर्ता',
      'sve': 'सहेजें',
      'snd': 'संदेश',
      'svdpsts': 'सहेजे गए पोस्ट',
      'stngs': 'Settings',
      'shr': 'शेयर',
      'shwpinf': 'व्यक्तिगत जानकारी दिखाएँ',
      'sgnplgn': 'साइन अप / लॉगिन',
      'bcyato': 'कंटीन्यू करके, आप सहमत हैं हमारे',
      'trmscndtn': 'नियम और शर्तें',
      'nndd': 'और',
      'prvplcy': 'गोपनीयता नीति',
      'cntctus': 'हमसे संपर्क करें',
      'mycht': 'माय चैट्स',
      'ntf': 'सूचनाएं',
      'prfl': 'प्रोफाइल',
      'slctcntry': 'अपना देश चुनें',
      'srch': 'खोज',
      'rfrshng': 'रिफ्रेशिंग ...',
      'nmrrcrds': 'नो रिकॉर्ड्स',
      'ldng': 'लोड हो रहा है ...',
      'ldmr': 'अधिक लोड करें ...',
      'msg': 'संदेश',
      'cmnt': 'टिप्पणी',
      'cht': 'चैट',
      'nxt': 'नेक्स्ट',
      'nic': 'कोई इंटरनेट कनेक्शन नहीं।',
      'flwng': 'फ़ॉलो',
      'flwrs': 'फॉलोअर्स',
      'chlng': 'भाषा बदलें',
      'hlp': 'सहायता',
      'myprfl': 'माई प्रोफाइल',
      'adpht': 'फोटो जोड़ें',
      'mob': 'फ़ोन नंबर',
      'eml': 'ईमेल',
      'lgt': 'लॉग आउट',
      'eemlphn': 'ईमेल या फ़ोन नंबर दर्ज करें',
      'emlphntvld': 'ईमेल या फ़ोन नंबर मान्य नहीं है',
      'etrpswrd': 'पासवर्ड दर्ज करें',
      'pswrdntvld': 'पासवर्ड मान्य नहीं है',
      'lgn': 'लॉग इन',
      'emlrph': 'ईमेल या फ़ोन नंबर',
      'psswrd': 'पासवर्ड',
      'frgtpswrd': 'पासवर्ड भूल गए?',
      'sgnup': 'साइन अप',
      'emlphntrgsrd': 'ईमेल या फ़ोन नंबर पंजीकृत नहीं है',
      'gndr': 'जेंडर',
      'dobrth': 'जन्म तिथि',
      'nvldpswrd8': 'अमान्य पासवर्ड, न्यूनतम लंबाई 8 अंक है',
      'ml': 'पुरुष',
      'fml': 'महिला',
      'penm': 'कृपया पहला नाम दर्ज करें',
      'frstnm': 'पहला नाम',
      'pelnm': 'कृपया अंतिम नाम दर्ज करें',
      'lstnm': 'लास्ट नेम',
      'plzvldphn': 'कृपया एक मान्य फ़ोन नंबर दर्ज करें',
      'pswdnt': 'पासवर्ड और पुष्टि पासवर्ड समान नहीं हैं',
      'cnfrmpswrd': 'पासवर्ड की पुष्टि करें',
      'rtry': 'रिट्री',
      'emlntvld': 'ईमेल मान्य नहीं है',
      'xcptn': 'कुछ गलत हो गया कृपया फिर से कोशिश करें',
      'nopsts': 'उफ्फ नो रिकॉर्ड मिली।',
      'ausywtlgt': 'क्या आप वाकई एप्लिकेशन से लॉग आउट करना चाहते हैं?',
      'ausywtdlt': 'क्या आप वाकई अपना खाता हटाना चाहते हैं?',
    },
  };

  // String getMessageByKey(appLanguageCode,String key) {
  //   return _localizedValues[locale.languageCode][key];
  // }
  String getMessageByLangAndKey(String appLanguageCode, String key) {
    String val = _localizedValues[appLanguageCode][key];
    return val ?? 'No Value for this string: $key';
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
